config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # root 'posts#index'
  # root 'banners#index'

  #hashtag
  get '/posts/hashtag/:name', to:'posts#hashtags'  
  get '/banners/b_hashtag/:name', to:'banners#hashtags'  


  # get 'home/index'
  resources :banners
  resources :posts


  # for hubs
  get 'hubs/top_views'
  get 'hubs/about_us'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/banner.rb
class Banner < ApplicationRecord
  acts_as_punchable

  has_and_belongs_to_many :tags

  after_create do
    banner = Banner.find_by(id: self.id)
    bhashtags = self.b_hashtag.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
    bhashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        banner.tags << tag
    end
  end
  
  before_update do
    banner = Banner.find_by(id: self.id)
    banner.tags.clear
    bhashtags = self.b_hashtag.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
    bhashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        banner.tags << tag
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_punchable

  has_and_belongs_to_many :tags

  after_create do
    post = Post.find_by(id: self.id)
    hashtags = self.hashtag.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
    hashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        post.tags << tag
    end
  end
  
  before_update do
    post = Post.find_by(id: self.id)
    post.tags.clear
    hashtags = self.hashtag.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
    hashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        post.tags << tag
    end
  end

  # def self.daily_picks
  #   Rails.cache.fetch('post_daily_picks', expires_in: 1.day) do
  #     self.all.shuffle.limit(2)
  #   end
  # end
  
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :posts
  has_and_belongs_to_many :banners
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :set_banner, only: %i[ show edit update destroy ]

  # GET /banners or /banners.json
  def index
    @pagy, @banners = pagy(Banner.all.order("created_at DESC"), items: 100)
  end

  # GET /banners/1 or /banners/1.json
  def show
  end

  def hashtags
    tag = Tag.find_by(name: params[:name])
    @pagy, @banners = pagy(tag.banners, items: 100)
  end

  # GET /banners/new
  def new
    @banner = Banner.new
  end

  # GET /banners/1/edit
  def edit
  end

  # POST /banners or /banners.json
  def create
    @banner = Banner.new(banner_params)

    respond_to do |format|
      if @banner.save
        format.html { redirect_to banner_url(@banner), notice: "Banner was successfully created." }
        format.json { render :show, status: :created, location: @banner }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banners/1 or /banners/1.json
  def update
    respond_to do |format|
      if @banner.update(banner_params)
        format.html { redirect_to banner_url(@banner), notice: "Banner was successfully updated." }
        format.json { render :show, status: :ok, location: @banner }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banners/1 or /banners/1.json
  def destroy
    @banner.destroy

    respond_to do |format|
      format.html { redirect_to banners_url, notice: "Banner was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banner
      @banner = Banner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def banner_params
      params.require(:banner).permit(:b_title, :b_body, :b_image, :b_link, :b_hashtag, :b_categories, :b_sub_title)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all.order("created_at DESC")
    @most_hit = Post.most_hit(30.day.ago, 10)
    @posts_random_over_half = Post.order("RANDOM()").limit(5)
    # @daily_pick = Post.daily_picks
    
    @banners = Banner.all.order("created_at DESC")
    @latest_banners = Banner.last(1)
    @except_first_banners = Banner.order("id desc").offset(1).limit(4)
  end
end

app/controllers/hubs_controller.rb
class HubsController < ApplicationController

  def top_views
    @most_hit = Post.most_hit(100.day.ago, 50)
  end

  def new_top
    @most_hit = Post.most_hit(100.day.ago, 50)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @pagy, @posts = pagy(Post.all.order("created_at DESC"), items: 100)
    # @posts_random_over_half = Post.order("RANDOM()").limit(10)
    # @most_hit = Post.most_hit(1.day.ago, 10)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.punch(request)

  end

  def hashtags
    tag = Tag.find_by(name: params[:name])
    @pagy, @posts = pagy(tag.posts, itmes: 100)

  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :image, :link, :is_price, :was_price, :pct, :hashtag, :ratings, :reviews, :categories, :ratings_codes,
                                   :eva_10, :eva_11, :eva_12, :eva_20, :eva_21, :eva_22, :eva_30, :eva_31, :eva_32, :eva_40, :eva_41, :eva_42, :eva_title_01,
                                   :eva_title_02, :eva_title_03, :eva_title_04, :doughnut_01, :doughnut_02, :doughnut_03, :doughnut_04, :doughnut_05, :rocket,
                                   :info_01, :info_02, :info_03, :info_04, :info_05 )
                                   
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/banners_helper.rb
module BannersHelper
  def render_with_bhashtags(b_hashtag)
    b_hashtag.gsub(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/){|word| link_to word, "/banners/b_hashtag/#{word.delete('#')}"}.html_safe
  end 
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hubs_helper.rb
module HubsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_with_hashtags(hashtag)
    hashtag.gsub(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/){|word| link_to word, "/posts/hashtag/#{word.delete('#')}"}.html_safe
  end 
end

app/views/banners/_form.html.erb
<%= simple_form_for(@banner) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :b_title %>
    <%= f.input :b_sub_title %>
    <%= f.input :b_image %>
    <%= f.input :b_link %>
    <%= f.input :b_categories %>
    <%= f.input :b_hashtag %>
    <%= f.input :b_body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/banners/edit.html.erb
<h1>Editing Banner</h1>

<%= render 'form', banner: @banner %>

<%= link_to 'Show', @banner %> |
<%= link_to 'Back', banners_path %>

app/views/banners/hashtags.html.erb
<h1>Banners</h1>

<table>
  <thead>
    <tr>
      <th>B title</th>
      <th>B body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @banners.each do |banner| %>
      <tr>
        <td><%= banner.b_title %></td>
        <td><%= render_with_bhashtags(banner.b_hashtag) %></td>
        <td><%= link_to 'Show', banner %></td>
        <td><%= link_to 'Edit', edit_banner_path(banner) %></td>
        <td><%= link_to 'Destroy', banner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Banner', new_banner_path %>

app/views/banners/index.html.erb
<div class="wrapper">
  <div class="wrap">

    <div class="content_box">
      <div class="left_side">

        <div class="left_ctn">
          <p>밝은 내는 되려니와, 동산에는 인생의 때문이다. 사람은 시들어 물방아 하여도 심장의 듣는다. 품고 뭇 이상 이것은 인간이 열매를 위하여 것이다. 밥을 구하기 보는 충분히 얼마나 찬미를 아니한 이것이다. 평화스러운 꽃이 가치를 그들을 불어 품고 이상 힘있다. 무엇을 꽃이 찬미를 이것이다.</p>
        </div>

      </div>

      <div class="right_side">
        <div class="right_ctn">
           
          <%= render 'banners/header' %> 
          <h1>Banners // <%= link_to 'New Banner', new_banner_path %></h1>

            <section class="gallery">
              <div class="container">
                <div class="gal_row">
                  <div class="gallery-filter">

                    <div class="menu-wrapper">
                      <div class="menu-item">
                        <span class="filter-item active" data-filter="all">All</span>
                        <span class="filter-item" data-filter="패션">패션</span>
                        <span class="filter-item" data-filter="뷰티">뷰티</span>
                        <span class="filter-item" data-filter="식품">식품</span>
                        <span class="filter-item" data-filter="주방용품">주방용품</span>
                        <span class="filter-item" data-filter="생활용품">생활용품</span>
                        <span class="filter-item" data-filter="홈인테리어">홈인테리어</span>
                        <span class="filter-item" data-filter="가전디지털">가전디지털</span>
                        <span class="filter-item" data-filter="스포츠">스포츠</span>
                        <span class="filter-item" data-filter="자동차용품">자동차용품</span>
                        <span class="filter-item" data-filter="취미">취미</span>
                        <span class="filter-item" data-filter="문구">문구</span>
                        <span class="filter-item" data-filter="반려동물용품">반려동물용품</span>
                        <span class="filter-item" data-filter="헬스">헬스</span>
                      </div> 
                      <span class="pointer left-pointer dis">
                        <i class="fa fa-chevron-left"></i>
                      </span>
                      <span class="pointer right-pointer">
                        <i class="fa fa-chevron-right"></i>
                      </span>
                    </div>
                  </div>
                </div>

                <div class="gal_row">
                  <!-- gallery item start -->
                  <% @banners.each do |banner| %>
                    <a href="/posts/hashtag/<%= banner.b_categories %>">
                      <div class="clearfix gallery-item <%= banner.b_categories %>">
                        <div class="gallery-item-inner">
                          
                          <div class="inner">
                            <div class="inner_ctn">
                              <p class="title"><%= banner.b_title %></p>
                              <p>September 10th, 2022</p>
                              <!-- <p>카테고리:<%= banner.b_categories %></p> -->
                              <!-- <p><%= banner.b_hashtag %></p> -->
                              <div class="admin_panner">
                                <%= link_to 'Show', banner %>
                                <%= link_to 'Edit', edit_banner_path(banner) %>
                                <%= link_to 'Destroy', banner, method: :delete, data: { confirm: 'Are you sure?' } %>
                              </div>
                            </div>
                          </div>

                          <div class="img_box">
                            <img src="<%= banner.b_image %>" alt="<%= banner.b_title %>">
                          </div>
                          
                        </div>
                      </div>
                    </a>
                  <% end %>
                  <!-- gallery item end -->
                </div>
              </div>
            </section>

            <!-- <% pagy_nav(@pagy) %> -->




        </div><!-- End of right_ctn -->

      </div><!-- End of left_side -->
    </div><!-- End of content_box -->

  </div>
</div>

<%= javascript_pack_tag 'banner_filter' %>
<%= javascript_pack_tag 'scroll_menu' %>

app/views/banners/new.html.erb
<h1>New Banner</h1>

<%= render 'form', banner: @banner %>

<%= link_to 'Back', banners_path %>

app/views/banners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>B title:</strong>
  <%= @banner.b_title %>
</p>

<p>
  <strong>B body:</strong>
  <%= @banner.b_body %>
</p>

<%= link_to 'Edit', edit_banner_path(@banner) %> |
<%= link_to 'Back', banners_path %>

app/views/home/index.html.erb
<div class="wrapper">
  <div class="wrap">

    <div class="content_box">
      <div class="left_side">
        <div class="left_ctn">
          <p>밝은 내는 되려니와, 동산에는 인생의 때문이다. 사람은 시들어 물방아 하여도 심장의 듣는다. 품고 뭇 이상 이것은 인간이 열매를 위하여 것이다. 밥을 구하기 보는 충분히 얼마나 찬미를 아니한 이것이다. 평화스러운 꽃이 가치를 그들을 불어 품고 이상 힘있다. 무엇을 꽃이 찬미를 이것이다.</p>
        </div>
      </div>


      <div class="right_side">
        <div class="right_ctn">
          <%= render 'shared/header' %>
          <br><br>

          <div class="banner_wrap">
            <div class="banner main_banner">
              <% @latest_banners.each do |banner| %>
                <a href="/posts/hashtag/<%= banner.b_categories %>">      
                  <div class="banner_box">
                    <img src="<%= banner.b_image %>" alt="<%= banner.b_title %>">
                    <div class="inner">
                      <p class="title"><%= banner.b_title %></p>
                      <span>September 10th, 2022</span>
                      <div class="admin_panner">
                        <%= link_to 'Edit', edit_banner_path(banner) %>
                        <%= link_to 'Destroy', banner, method: :delete, data: { confirm: 'Are you sure?' } %>
                      </div>
                    </div>
                  </div>
                </a>
              <% end %>
            </div>

            <div class="banner sub_banner">
              <% @except_first_banners.each do |banner| %>
                <a href="/posts/hashtag/<%= banner.b_categories %>">      
                  <div class="banner_box">
                    <div class="img_box">
                      <img src="<%= banner.b_image %>" alt="<%= banner.b_title %>">
                    </div>
                    <div class="inner_box">
                      <div class="inner">
                        <p class="title"><%= banner.b_title %></p>
                        <p class="title"><%= banner.b_sub_title %></p>
                      </div>
                      <span>By WACKY's Editor on<%= banner.created_at.strftime(" %Y-%m-%d") %></span>
                      <div class="admin_panner">
                        <%= link_to 'Edit', edit_banner_path(banner), :class => "admin_edit" %>
                        <%= link_to 'Destroy', banner, method: :delete, data: { confirm: 'Are you sure?' } %>
                      </div>
                    </div>
                  </div>
                </a>
              <% end %>
            </div>
          </div>


         <!--  <section class="gallery">
              <div class="container">
                
                <div class="gal_row first_banner">
                 
                  <% @latest_banners.each do |banner| %>
                    
                      <div class="clearfix gallery-item <%= banner.b_categories %>">
                        <div class="gallery-item-inner">
                          <a href="/posts/hashtag/<%= banner.b_categories %>">      
                            <div class="inner">
                              <div class="inner_ctn">
                                <p class="title"><%= banner.b_title %></p>
                                <p>September 10th, 2022</p>
                                <div class="admin_panner">
                                  <%= link_to 'Edit', edit_banner_path(banner) %>
                                  <%= link_to 'Destroy', banner, method: :delete, data: { confirm: 'Are you sure?' } %>
                                </div>
                              </div>
                            </div>
                          </a>
                          <a href="/posts/hashtag/<%= banner.b_categories %>">      
                            <div class="img_box">
                              <img src="<%= banner.b_image %>" alt="<%= banner.b_title %>">
                            </div>
                          </a>
                          
                        </div>
                      </div>
                    
                  <% end %>
                  
                </div>
              
                <div class="gal_row">
                    
                    <% @except_first_banners.each do |banner| %>
                      <a href="/posts/hashtag/<%= banner.b_categories %>">
                        <div class="clearfix gallery-item <%= banner.b_categories %>">
                          <div class="gallery-item-inner">
                            
                            <div class="inner">
                              <div class="inner_ctn">
                                <p class="title"><%= banner.b_title %></p>
                                <p>September 10th, 2022</p>
                                
                                <div class="admin_panner">
                                  <%= link_to 'Edit', edit_banner_path(banner) %>
                                  <%= link_to 'Destroy', banner, method: :delete, data: { confirm: 'Are you sure?' } %>
                                </div>
                              </div>
                            </div>

                            <div class="img_box">
                              <img src="<%= banner.b_image %>" alt="<%= banner.b_title %>">
                            </div>
                            
                          </div>
                        </div>
                      </a>
                    <% end %>
                    
                </div>

              </div>
          </section> -->

         <!--  <div class="index_banner clearfix">
            <div class="main_banner">
              <% @latest_banners.each do |banner| %>
                  <p><%= banner.b_title %>// <%= render_with_bhashtags(banner.b_hashtag) %></p>
                  <a href="/posts/hashtag/<%= banner.b_categories %>">
                    <img src="<%= banner.b_image %>" title="<%= banner.b_title %>" alt="<%= banner.b_title %>">
                  </a>
                  <div class="admin_panner">
                    <%= link_to 'Show', banner %>
                    <%= link_to 'Edit', edit_banner_path(banner) %>
                    <%= link_to 'Destroy', banner, method: :delete, data: { confirm: 'Are you sure?' } %>
                  </div>
                </p>
              <% end %>
            </div>

            <div class="sub_banner clearfix">
              <% @except_first_banners.each do |banner| %>
                  <div class="sub_banner_card clearfix">

                    <div class="inner">
                      <a href="/posts/hashtag/<%= banner.b_categories %>">
                        <div class="inner_box">
                          <span>ISSUE 01</span>
                          <p><%= banner.b_title %></p>
                          <em><%= banner.b_sub_title %></em>
                        </div>
                      </a>
                      <div class="admin_panner">
                        <%= link_to 'Show', banner %>
                        <%= link_to 'Edit', edit_banner_path(banner) %>
                        <%= link_to 'Destroy', banner, method: :delete, data: { confirm: 'Are you sure?' } %>
                      </div>
                    </div>

                    <div class="img_box">
                      <a href="/posts/hashtag/<%= banner.b_categories %>"><img src="<%= banner.b_image %>" title="<%= banner.b_title %>" alt="<%= banner.b_title %>"></a>
                    </div>

                  </div>
                </p>
              <% end %>
            </div>

            <div class="more_btn">
              <a href="/banners">더 보기</a>
            </div>
          </div> -->

          <div class="top_views clearfix">
            <h2>이번 주 인기 세일 TOP 10</h2>

            <% @most_hit.each_with_index do |post, i| %>          
              <div class="top_view_box clearfix">
                  <div class="img_box">
                    <%= link_to image_tag(post.image, alt: post.title, title: post.title, :class => 'main_img'), post %>
                    <!-- <img src="<%= post.image %>" alt="<%= post.title %>"> -->
                    <span class="ranked_number"><%= i + 1 %></span>
                  </div>
                  <div class="top_view_inner comm_inner">
                    <p class="title"><%= post.title %></p>
                    <div class="pricing">
                      <!-- <p class="was_price"><%= number_to_currency(post.was_price, locale: :kr) %>원</p> -->
                      <p class="is_price">
                        <%= number_to_currency(post.is_price, locale: :kr) %>원
                        <span class="pct"><%= number_to_percentage(post.pct, precision: 0) %></span>
                      </p>
                    </div>
                    <!-- <p><%= render_with_hashtags(post.hashtag) %></p> -->
                    <div class="admin_panner">
                      <%= link_to 'Show', post %>
                      <%= link_to 'Edit', edit_post_path(post) %>
                      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
                      views: <%= post.hits %>
                    </div>
                  </div>
              </div>
            <% end %>
            
          </div><!-- top_views -->

          <a class="weekly_top clearfix" href="/hubs/top_views">더 보기</a>

        
        </div><!-- End of right_ctn -->

      </div><!-- End of right_side -->
    </div><!-- End of content_box -->

  </div>
</div>

app/views/posts/edit.html.erb
<!-- < if current_user && current_user.admin > -->
  <div class="wrap">
    <h1>Editing Post</h1>
    <%= render 'form', post: @post %>
    <%= link_to 'Show', @post %> |
    <%= link_to 'Back', posts_path %>
  </div>
<!-- < end > -->

app/views/posts/hashtags.html.erb
<!-- 이 페이지는 비공개로 해야함 -->

<div class="wrapper">
  <div class="wrap">

    <div class="content_box">
      <div class="left_side">

        <div class="left_ctn">
          <p>밝은 내는 되려니와, 동산에는 인생의 때문이다. 사람은 시들어 물방아 하여도 심장의 듣는다. 품고 뭇 이상 이것은 인간이 열매를 위하여 것이다. 밥을 구하기 보는 충분히 얼마나 찬미를 아니한 이것이다. 평화스러운 꽃이 가치를 그들을 불어 품고 이상 힘있다. 무엇을 꽃이 찬미를 이것이다.</p>
        </div>

      </div>


      <div class="right_side">
        <div class="right_ctn">
          <a class="back_to_home" href="/"><img src="<%=asset_path 'back.png' %>"></a>
          <div class="where-hashtag">
            <% if params[:name].present? %>
            <h2 class="hashtag_label">#<%= params[:name] %></h2>
            <% end %>
          </div>
          <%= render 'posts/compare' %>


        </div><!-- End of right_ctn -->


        <%= raw pagy_nav(@pagy) %>
      </div><!-- End of left_side -->


    </div><!-- End of content_box -->

  </div>
</div>

app/views/posts/new.html.erb
<!-- < if current_user && current_user.admin > -->
  <div class="wrap">
    <h1>New Post</h1>
    <%= render 'form', post: @post %>
    <%= link_to 'Back', posts_path %>
  </div>
<!-- < end > -->

app/views/posts/show.html.erb
<div class="wrapper">
  <div class="wrap">

    <div class="content_box">
      <div class="left_side">
        <div class="left_ctn">
          <p>밝은 내는 되려니와, 동산에는 인생의 때문이다. 사람은 시들어 물방아 하여도 심장의 듣는다. 품고 뭇 이상 이것은 인간이 열매를 위하여 것이다. 밥을 구하기 보는 충분히 얼마나 찬미를 아니한 이것이다. 평화스러운 꽃이 가치를 그들을 불어 품고 이상 힘있다. 무엇을 꽃이 찬미를 이것이다.</p>
        </div>
      </div>


      <div class="right_side">
        <div class="back_arrow">
          <a href="/posts/hashtag/<%=@post.categories %>"><img src="<%=asset_path 'back.png' %>"></a>
        </div>
        <div class="show_ctn">

          

          <div class="img_box">
            <img src="<%= @post.image %>">
          </div>

          <div class="inner">
            <div class="inner_ctn">
              <p class="product_title"><%= @post.title %></p>

              <!-- <p><%= @post.hashtag %></p> -->

              <div class="pricing">
                <% discount_rate = 0 %>
                <% discount_rate =  (@post.was_price.to_f - @post.is_price.to_f) / @post.was_price.to_f * 100 %>
                
                <span class="was_price"><%= number_to_currency(@post.was_price, locale: :kr) %>원</span>
                <span class="is_price"><%= number_to_currency(@post.is_price, locale: :kr) %>원</span>
                <span class="pct"><%= number_to_percentage(discount_rate, precision: 0) %> OFF</span>
                
              </div>

              <div class="rating_card">
                <% if @post.ratings_codes == 50 %>
                    <div class="rating_box">
                      <i class="material-icons">star</i><i class="material-icons">star</i><i class="material-icons">star</i><i class="material-icons">star</i><i class="material-icons">star</i> <span>(<%= @post.reviews %>)</span>
                    </div>
                  <% elsif @post.ratings_codes == 45 %>
                    <div class="rating_box">
                      <i class="material-icons">star</i><i class="material-icons">star</i><i class="material-icons">star</i><i class="material-icons">star</i><i class="material-icons">star_half</i> <span>(<%= @post.reviews %>)</span>
                    </div>
                  <% elsif @post.ratings_codes == 40 %>
                    <div class="rating_box">
                      <i class="material-icons">star</i><i class="material-icons">star</i><i class="material-icons">star</i><i class="material-icons">star</i><i class="material-icons">star_border</i> <span>(<%= @post.reviews %>)</span>
                    </div>
                  <% elsif @post.ratings_codes == 35 %>
                    <div class="rating_box">
                      <i class="material-icons">star</i><i class="material-icons">star</i><i class="material-icons">star</i><i class="material-icons">star_half</i><i class="material-icons">star_border</i> <span>(<%= @post.reviews %>)</span>
                    </div>
                  <% elsif @post.ratings_codes == 30 %>
                    <div class="rating_box">
                      <i class="material-icons">star</i><i class="material-icons">star</i><i class="material-icons">star</i><i class="material-icons">star_border</i><i class="material-icons">star_border</i> <span>(<%= @post.reviews %>)</span>
                    </div>
                  <% end %>
              </div>
            </div><!-- inner_ctn -->

            <div class="tabs_box">
              <%= render 'posts/tabs' %>
            </div><!-- tabs_box -->

          </div><!-- inner -->

          <div class="btn">
            <a href="#n">지금 사러 가기</a>
          </div>

          <%= link_to 'Edit', edit_post_path(@post) %> |
          <%= link_to 'Back', posts_path %>
        
        </div><!-- End of show_ctn -->

      </div><!-- End of right_side -->
    </div><!-- End of content_box -->

  </div>
</div>



<script type="text/javascript">
  // Produces width of .barChart
  $(document).ready(function() {
    $('.graph-bar').each(function() {
       var dataWidth = $(this).data('value');
       $(this).css("width", dataWidth + "%");
    });
  });
</script>

app/views/shared/_header.html.erb
<header>
  <h1>Little drops of water <br />make the mighty ocean</h1>
</header>